apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: null
  name: jira-release
spec:
  stepTemplate:
    env:
    - name: HOME
      value: /tekton/home
    envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    name: ""
    resources: {}
    workingDir: /workspace/source    
  steps:
  - image: ghcr.io/jenkins-x/jx-boot:3.10.124
    name: jx-variables
    resources: {}
    script: |
      #!/usr/bin/env sh
      jx gitops variables  
  - image: ghcr.io/jenkins-x/jx-boot:3.10.124
    name: git-history
    resources: {}
    script: |
      #!/usr/bin/env sh -x
      git fetch --prune --tags --force  
  - image: ghcr.io/jenkins-x/jx-boot:3.10.124
    name: collect-issues
    resources: {}
    script: |
      #!/usr/bin/env sh -x
      git log $(git describe --abbrev=0 --tags 2> /dev/null || git rev-list --max-parents=0 HEAD) | \
        grep -oE "$JIRA_PROJECT-[[:digit:]]{1,}" | sort | uniq | \
        paste -sd , - | awk '{print "\"" $0 "\""}' > JIRA_ISSUES
  - envFrom:
    - secretRef:
        name: jx-boot-job-env-vars
        optional: true
    image: curlimages/curl:7.72.0
    name: invoke-jira-webhook
    resources: {}
    script: |
      #!/bin/sh -x
      export RELATED_JIRA_ISSUES=$(cat ./JIRA_ISSUES)
      echo JIRA Tickets are: $RELATED_JIRA_ISSUES
      curl -XPOST -H "Content-Type: application/json" -d '{"data": {"version": "'"$APP_NAME - $VERSION"'","projectname": "'"$JIRA_PROJECT"'"}, "issues": ['"$RELATED_JIRA_ISSUES"']}' $JIRA_WEBHOOK_URL
  workspaces:
  - description: The git repo will be cloned onto the volume backing this workspace
    mountPath: /workspace/source
    name: output
