apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: OKTETO_DOMAIN
            value: predev.jaraxa.systems         
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.10.45
          name: jx-variables
          resources:
            # set requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: ghcr.io/jenkins-x/jx-registry:0.1.8
          name: check-registry
          resources: {}
        - image: okteto/okteto:2.12.0
          name: okteto-context
          resources: {}
          script: |
            #!/bin/bash
            okteto context -l debug use $OKTETO_URL -n $OKTETO_NAMESPACE -t $OKTETO_TOKEN
        - image: okteto/okteto:2.12.0
          name: okteto-build
          resources: {}
          script: |
            #!/bin/bash
            cp .env_docker .env
            okteto build -f $OKTETO_COMPOSE -n $KOMPOSE_NAMESPACE            
        - image: okteto/okteto:2.12.0
          name: okteto-deploy
          resources: {}
          script: |
            #!/bin/bash
            okteto deploy --wait -f $OKTETO_COMPOSE -n $KOMPOSE_NAMESPACE
        - image: okteto/okteto:2.12.0
          name: okteto-destroy
          resources: {}
          script: |
            #!/bin/bash
            okteto destroy -f $OKTETO_COMPOSE -n $KOMPOSE_NAMESPACE -v
        - image: minio/mc
          name: okteto-create-buckets
          resources: {}
          script: |
            #!/bin/bash
            mc alias set myminio http://$MINIO_SERVICE.$KOMPOSE_NAMESPACE.svc.cluster.local:9000 minio minio123;
            mc mb -p myminio/pet-files;
            mc policy set public myminio/pet-files;
            exit 0;
        - image: continuul/build-essential
          name: okteto-tests-curl
          resources: {}
          script: |
            #!/bin/bash
            make $OKTETO_TARGET
            echo "Visit https://ci-ui-kompose.${OKTETO_DOMAIN}/ to get tests result report"
            echo "Login: admin@jaraxa.com / 12345678"
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
