apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.9.5
          name: jx-variables
          resources:
            # set requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: ghcr.io/jenkins-x/jx-registry:0.1.8
          name: check-registry
          resources: {}
        - image: okteto/okteto:2.9.1
          name: okteto-context
          resources: {}
          script: |
            #!/bin/bash
            okteto context -l debug use $OKTETO_URL -n $OKTETO_NAMESPACE -t $OKTETO_TOKEN
        - image: okteto/okteto:2.9.1
          name: okteto-build
          resources: {}
          script: |
            #!/bin/bash
            okteto build -f $OKTETO_COMPOSE -n $KOMPOSE_NAMESPACE            
        - image: okteto/okteto:2.9.1
          name: okteto-deploy
          resources: {}
          script: |
            #!/bin/bash
            okteto deploy --wait -f $OKTETO_COMPOSE -n $KOMPOSE_NAMESPACE
        - image: okteto/okteto:2.9.1
          name: okteto-destroy
          resources: {}
          script: |
            #!/bin/bash
            okteto destroy -f $OKTETO_COMPOSE -n $KOMPOSE_NAMESPACE -v
        - image: minio/mc
          name: okteto-create-buckets
          resources: {}
          script: |
            #!/bin/bash
            mc alias set myminio https://dkv-pet-minio-kompose.develop.jaraxa.systems minio minio123;
            mc mb -p myminio/pet-files;
            mc policy set public myminio/pet-files;
            exit 0;
        - image: continuul/build-essential
          name: okteto-tests-curl
          resources: {}
          script: |
            #!/bin/bash
            make $OKTETO_TARGET
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
