apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: OKTETO_URL
            value: ""
          - name: OKTETO_NAMESPACE
            value: ""
          - name: OKTETO_TOKEN
            value: ""
          - name: OKTETO_COMPOSE
            value: docker-compose.yaml
          - name: KOMPOSE_NAMESPACE
            value: ""
          - name: OKTETO_TARGET
            value: ""
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.9.5
          name: jx-variables
          resources:
            # set requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: ghcr.io/jenkins-x/jx-registry:0.1.8
          name: check-registry
          resources: {}
        - image: okteto/okteto:2.9.1
          name: okteto-context
          resources: {}
          script: |
            #!/bin/bash
            okteto context use $OKTETO_URL -n $OKTETO_NAMESPACE -t $OKTETO_TOKEN
        - image: okteto/okteto:2.9.1
          name: okteto-build
          resources: {}
          script: |
            #!/bin/bash
            okteto build -f $OKTETO_COMPOSE -n $KOMPOSE_NAMESPACE            
        - image: okteto/okteto:2.9.1
          name: okteto-deploy
          resources: {}
          script: |
            #!/bin/bash
            okteto deploy --wait -f $OKTETO_COMPOSE -n $KOMPOSE_NAMESPACE
        - image: okteto/okteto:2.9.1
          name: okteto-destroy
          resources: {}
          script: |
            #!/bin/bash
            okteto destroy -f $OKTETO_COMPOSE -n $KOMPOSE_NAMESPACE -v
        - image: minio/mc
          name: okteto-create-buckets
          resources: {}
          script: |
            #!/bin/bash
            mc alias set myminio https://dkv-pet-minio-kompose.develop.jaraxa.systems minio minio123;
            mc mb -p myminio/pet-files;
            mc policy set public myminio/pet-files;
            exit 0;
        - image: curlimages/curl
          name: okteto-tests-curl
          resources: {}
          args: [
          	"--write-out",
            "'%{http_code}\n'",
            "--silent",
            "--output /dev/null",
            "-XPOST -i -H "content-type: application/json" -H "x-netcomposer-auth: YWRtaW46bmV0Y29tcG9zZXI=" ${SHP_API_URL_OKT} -d '{ "cmd": "objects/node/load_objs", "data": {"objs": [{"path": "/file.stores/local", "type": "file.store", "file.store": {"class": "filesystem", "config": {"path": "/files.stores/local"}}}]}}'"
          ]
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
