apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: LIQUIBASE_COMMAND_USERNAME
            value: postgres
          - name: LIQUIBASE_COMMAND_REFERENCE_USERNAME
            value: postgres
          - name: LIQUIBASE_COMMAND_CHANGELOG_FILE
            value: liquibase/changelog-master.xml
          - name: LIQUIBASE_SEARCH_PATH
            value: src/main/resources/
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            limits: {}
          workingDir: /workspace/source
        steps:
        - name: liquibase-validate
          image: liquibase/liquibase:4.27
          resources: {}          
          script: |
            #!/bin/bash
            export LIQUIBASE_COMMAND_PASSWORD=$(cat preview/PG_PASSWORD_PREVIEW)
            export PREVIEW_NAMESPACE=$(cat preview/PREVIEW_NAMESPACE)

            liquibase validate --url jdbc:postgresql://preview-dkv-pet-cloud-postgres.${PREVIEW_NAMESPACE}.svc.cluster.local:5432/pet
        - name: liquibase-update-rollback-update
          image: liquibase/liquibase:4.27
          resources: {}          
          script: |
            #!/bin/bash
            export LIQUIBASE_COMMAND_PASSWORD=$(cat preview/PG_PASSWORD_PREVIEW)
            export PREVIEW_NAMESPACE=$(cat preview/PREVIEW_NAMESPACE)

            liquibase update-testing-rollback --url jdbc:postgresql://preview-dkv-pet-cloud-postgres.${PREVIEW_NAMESPACE}.svc.cluster.local:5432/pet
        - name: liquibase-drop-db
          image: liquibase/liquibase:4.27
          resources: {}          
          script: |
            #!/bin/bash
            export LIQUIBASE_COMMAND_PASSWORD=$(cat preview/PG_PASSWORD)
            export PREVIEW_NAMESPACE=$(cat preview/PREVIEW_NAMESPACE)

            liquibase execute-sql --sql="DROP EXTENSION pg_stat_kcache CASCADE; DROP EXTENSION pg_stat_statements CASCADE;" --url jdbc:postgresql://preview-dkv-pet-cloud-postgres.${PREVIEW_NAMESPACE}.svc.cluster.local:5432/pet --username=postgres
            liquibase drop-all --url jdbc:postgresql://preview-dkv-pet-cloud-postgres.${PREVIEW_NAMESPACE}.svc.cluster.local:5432/pet --username=postgres
        - name: liquibase-history
          image: liquibase/liquibase:4.27
          resources: {}          
          script: |
            #!/bin/bash
            export LIQUIBASE_COMMAND_PASSWORD=$(cat preview/PG_PASSWORD_PREVIEW)
            export PREVIEW_NAMESPACE=$(cat preview/PREVIEW_NAMESPACE)

            liquibase history --url jdbc:postgresql://preview-dkv-pet-cloud-postgres.${PREVIEW_NAMESPACE}.svc.cluster.local:5432/pet
        - name: liquibase-diff
          image: liquibase/liquibase:4.27
          resources: {}          
          script: |
            #!/bin/bash
            export LIQUIBASE_COMMAND_PASSWORD=$(cat preview/PG_PASSWORD_DEVELOP)
            export LIQUIBASE_COMMAND_REFERENCE_PASSWORD=$(cat preview/PG_PASSWORD_PREVIEW)
            export PREVIEW_NAMESPACE=$(cat preview/PREVIEW_NAMESPACE)

            liquibase diff --reference-url jdbc:postgresql://preview-dkv-pet-cloud-postgres.${PREVIEW_NAMESPACE}.svc.cluster.local:5432/pet --url jdbc:postgresql://dkv-pet-cloud-postgres.jx-pet3-develop.svc.cluster.local:5432/pet        
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
