
# generated by: jx gitops variables
export APP_NAME='jaraxa-pipeline-catalog'
export BRANCH_NAME='master'
export BUILD_NUMBER='9'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='jaraxasoftware'
export DOMAIN='develop.jaraxa.systems'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard-jx3.develop.jaraxa.systems/jaraxasoftware/jaraxa-pipeline-catalog/master/9'
export JX_CHART_REPOSITORY='https://github.com/jaraxasoftware/jx3-jaraxa.git'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/jaraxasoftware/jaraxa-pipeline-catalog:0.3.8'
export NAMESPACE_SUB_DOMAIN='-jx3.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jaraxa-pipeline-catalog'
export REPO_OWNER='jaraxasoftware'
export VERSION='0.3.8'


# content from git...

# generated by: jx gitops variables
export APP_NAME='jaraxa-pipeline-catalog'
export BRANCH_NAME='master'
export BUILD_NUMBER='8'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='jaraxasoftware'
export DOMAIN='develop.jaraxa.systems'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard-jx3.develop.jaraxa.systems/jaraxasoftware/jaraxa-pipeline-catalog/master/8'
export JX_CHART_REPOSITORY='https://github.com/jaraxasoftware/jx3-jaraxa.git'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/jaraxasoftware/jaraxa-pipeline-catalog:0.3.7'
export NAMESPACE_SUB_DOMAIN='-jx3.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jaraxa-pipeline-catalog'
export REPO_OWNER='jaraxasoftware'
export VERSION='0.3.7'


# content from git...

# generated by: jx gitops variables
export APP_NAME='jaraxa-pipeline-catalog'
export BRANCH_NAME='master'
export BUILD_NUMBER='7'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='jaraxasoftware'
export DOMAIN='develop.jaraxa.systems'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard-jx3.develop.jaraxa.systems/jaraxasoftware/jaraxa-pipeline-catalog/master/7'
export JX_CHART_REPOSITORY='https://github.com/jaraxasoftware/jx3-jaraxa.git'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/jaraxasoftware/jaraxa-pipeline-catalog:0.3.6'
export NAMESPACE_SUB_DOMAIN='-jx3.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jaraxa-pipeline-catalog'
export REPO_OWNER='jaraxasoftware'
export VERSION='0.3.6'


# content from git...

# generated by: jx gitops variables
export APP_NAME='jaraxa-pipeline-catalog'
export BRANCH_NAME='master'
export BUILD_NUMBER='6'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='jaraxasoftware'
export DOMAIN='develop.jaraxa.systems'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard-jx3.develop.jaraxa.systems/jaraxasoftware/jaraxa-pipeline-catalog/master/6'
export JX_CHART_REPOSITORY='https://github.com/jaraxasoftware/jx3-jaraxa.git'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/jaraxasoftware/jaraxa-pipeline-catalog:0.3.5'
export NAMESPACE_SUB_DOMAIN='-jx3.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jaraxa-pipeline-catalog'
export REPO_OWNER='jaraxasoftware'
export VERSION='0.3.5'


# content from git...

# generated by: jx gitops variables
export APP_NAME='jaraxa-pipeline-catalog'
export BRANCH_NAME='master'
export BUILD_NUMBER='5'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='jaraxasoftware'
export DOMAIN='develop.jaraxa.systems'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard-jx3.develop.jaraxa.systems/jaraxasoftware/jaraxa-pipeline-catalog/master/5'
export JX_CHART_REPOSITORY='https://github.com/jaraxasoftware/jx3-jaraxa.git'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/jaraxasoftware/jaraxa-pipeline-catalog:0.3.4'
export NAMESPACE_SUB_DOMAIN='-jx3.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jaraxa-pipeline-catalog'
export REPO_OWNER='jaraxasoftware'
export VERSION='0.3.4'


# content from git...

# generated by: jx gitops variables
export APP_NAME='jaraxa-pipeline-catalog'
export BRANCH_NAME='master'
export BUILD_NUMBER='4'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='jaraxasoftware'
export DOMAIN='develop.jaraxa.systems'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard-jx3.develop.jaraxa.systems/jaraxasoftware/jaraxa-pipeline-catalog/master/4'
export JX_CHART_REPOSITORY='https://github.com/jaraxasoftware/jx3-jaraxa.git'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/jaraxasoftware/jaraxa-pipeline-catalog:0.3.3'
export NAMESPACE_SUB_DOMAIN='-jx3.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jaraxa-pipeline-catalog'
export REPO_OWNER='jaraxasoftware'
export VERSION='0.3.3'


# content from git...

# generated by: jx gitops variables
export APP_NAME='jaraxa-pipeline-catalog'
export BRANCH_NAME='master'
export BUILD_NUMBER='3'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='jaraxasoftware'
export DOMAIN='develop.jaraxa.systems'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard-jx3.develop.jaraxa.systems/jaraxasoftware/jaraxa-pipeline-catalog/master/3'
export JX_CHART_REPOSITORY='https://github.com/jaraxasoftware/jx3-jaraxa.git'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/jaraxasoftware/jaraxa-pipeline-catalog:0.3.2'
export NAMESPACE_SUB_DOMAIN='-jx3.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jaraxa-pipeline-catalog'
export REPO_OWNER='jaraxasoftware'
export VERSION='0.3.2'


# content from git...

# generated by: jx gitops variables
export APP_NAME='jaraxa-pipeline-catalog'
export BRANCH_NAME='master'
export BUILD_NUMBER='2'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='jaraxasoftware'
export DOMAIN='develop.jaraxa.systems'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard-jx3.develop.jaraxa.systems/jaraxasoftware/jaraxa-pipeline-catalog/master/2'
export JX_CHART_REPOSITORY='https://github.com/jaraxasoftware/jx3-jaraxa.git'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/jaraxasoftware/jaraxa-pipeline-catalog:0.3.1'
export NAMESPACE_SUB_DOMAIN='-jx3.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jaraxa-pipeline-catalog'
export REPO_OWNER='jaraxasoftware'
export VERSION='0.3.1'


# content from git...

# generated by: jx gitops variables
export APP_NAME='jaraxa-pipeline-catalog'
export BRANCH_NAME='master'
export BUILD_NUMBER='1'
export DOCKERFILE_PATH='Dockerfile'
export DOCKER_REGISTRY='ghcr.io'
export DOCKER_REGISTRY_ORG='jaraxasoftware'
export DOMAIN='develop.jaraxa.systems'
export GIT_BRANCH='master'
export JENKINS_X_URL='https://dashboard-jx3.develop.jaraxa.systems/jaraxasoftware/jaraxa-pipeline-catalog/master/1'
export JX_CHART_REPOSITORY='https://github.com/jaraxasoftware/jx3-jaraxa.git'
export KANIKO_FLAGS='--skip-unused-stages --snapshotMode=redo'
export MINK_AS='tekton-bot'
export MINK_IMAGE='ghcr.io/jaraxasoftware/jaraxa-pipeline-catalog:0.3.0'
export NAMESPACE_SUB_DOMAIN='-jx3.'
export PIPELINE_KIND='release'
export PUSH_CONTAINER_REGISTRY='ghcr.io'
export REPO_NAME='jaraxa-pipeline-catalog'
export REPO_OWNER='jaraxasoftware'
export VERSION='0.3.0'
















