apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.11.49
          name: jx-variables
          resources:
            # set requests for the pod here
            requests:
              cpu: 400m
              memory: 512Mi
          script: |
            #!/usr/bin/env sh
            jx gitops variables --commit=false
            jx gitops pr variables
        - args:
          - pr
          command:
          - make
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          image: ghcr.io/jenkins-x/jx-boot:3.11.49
          name: make-pr
          resources: {}
        - image: sonarsource/sonar-scanner-cli:11.0
          name: sonar-code-analisys
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh            
            sonar-scanner \
              -Dsonar.projectName=$APP_NAME \
              -Dsonar.token=$SONAR_TOKEN \
              -Dsonar.host.url=$SONAR_URL \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.branch.name=$PULL_BASE_REF \
              -Dsonar.inclusions=$SONAR_INCLUSIONS \
              -Dsonar.javascript.node.maxspace=8192
        - image: sonarsource/sonar-scanner-cli:11.0
          name: sonar-code-analisys-pr
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh            
            sonar-scanner \
              -Dsonar.projectName=$APP_NAME \
              -Dsonar.token=$SONAR_TOKEN \
              -Dsonar.host.url=$SONAR_URL \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.inclusions=$SONAR_EXCLUSIONS \
              -Dsonar.pullrequest.key=$PULL_NUMBER \
              -Dsonar.pullrequest.branch=$PR_HEAD_REF \
              -Dsonar.pullrequest.base=$PULL_BASE_REF \
              -Dsonar.scm.revision=$PR_HEAD_SHA \
              -Dsonar.javascript.node.maxspace=8192
        - image: uses:jaraxasoftware/jaraxa-pipeline-catalog/tasks/kubetest/environment.yaml@versionStream
          name: ""
          resources: {}
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
