apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: DIGITALOCEAN_ACCESS_TOKEN
            value: ""
          - name: CLUSTER_ID
            value: ""
          - name: CLUSTER_NAME
            value: ""
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            limits: {}
          workingDir: /workspace/source
        steps:
        - image: digitalocean/doctl:1.84.0
          name: doctl-ctx
          resources: {}
          script: |
            ./doctl kubernetes cluster kubeconfig save $CLUSTER_ID
        - image: ghcr.io/jenkins-x/jx-admin:0.0.174
          name: ctx-change
          script: |
            #!/usr/bin/env sh
            echo "Changing context to $CLUSTER_NAME cluster"
            jx ctx $CLUSTER_NAME
        - image: ghcr.io/jenkins-x/jx-admin:0.0.174
          name: admin-log
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          script: |
            #!/usr/bin/env sh
            echo "viewing the git operator boot job log for commit sha: $PULL_BASE_SHA"
            jx admin log --commit-sha $PULL_BASE_SHA
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
