apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: HOME
            value: /tekton/home
          - name: DIGITALOCEAN_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: do_token
                name: k8s-auth
          - name: GH_TOKEN
            valueFrom:
              secretKeyRef:
                key: password
                name: tekton-git
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: tekton-git                           
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            limits: {}
          workingDir: /workspace/source
        steps:
        - name: install-doctl
          image: alpine:3.16
          resources: {}
          script: |
            #!/bin/sh
            DOCTL_VERSION=1.100.0
            apk add --no-cache wget
            wget https://github.com/digitalocean/doctl/releases/download/v${DOCTL_VERSION}/doctl-${DOCTL_VERSION}-linux-amd64.tar.gz            
            tar xf ./doctl-${DOCTL_VERSION}-linux-amd64.tar.gz
            mkdir /workspace/source/bin
            mv ./doctl /workspace/source/bin/doctl
            chmod +x /workspace/source/bin/doctl
        - image: ghcr.io/jenkins-x/jx-boot:3.10.124
          name: do-ctx
          script: |
            #!/usr/bin/env sh
            echo "Saving context $CLUSTER_NAME"
            /workspace/source/bin/doctl kubernetes cluster kubeconfig save $CLUSTER_ID --verbose --trace
        - image: ghcr.io/jaraxasoftware/kubectx:latest
          name: ctx-change
          script: |
            #!/bin/bash
            echo "Changing context to $CLUSTER_NAME cluster"
            kubectl ctx $CLUSTER_NAME          
        - image: ghcr.io/jenkins-x/jx-admin:0.0.174
          name: admin-log
          resources: {}
          script: |
            #!/usr/bin/env sh
            echo "viewing the git operator boot job log for commit sha: $PULL_BASE_SHA"
            jx admin log --commit-sha $PULL_BASE_SHA
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
