apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: HOME
            value: /tekton/home
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: ghcr.io/jenkins-x/jx-boot:3.11.49
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
            jx gitops pr variables
        - image: haskell:8.10.4
          name: check-cabal
          resources: {}
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            echo "Running cabal update to ensure you're on latest dependencies..."
            cabal update
            echo "Cabal version is:"
            cabal --version
        - image: ghcr.io/jenkins-x/jx-registry:0.1.1
          name: check-registry
          resources: {}
        - image: ghcr.io/hadolint/hadolint:latest-debian
          name: check-dockerfile
          resources: {}
          script: |
            #!/usr/bin/env bash
            source .jx/variables.sh
            hadolint --no-fail Dockerfile
        - image: ghcr.io/jenkins-x/jx-boot:3.11.49
          name: build-helm-build
          resources: {}
          script: |
            #!/bin/sh
            jx gitops helm build
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
