apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          env:
          - name: HOME
            value: /tekton/home        
          envFrom:
          - secretRef:
              name: jx-boot-job-env-vars
              optional: true
          name: ""
          resources:
            requests:
              cpu: 800m
              memory: 1000Mi
          volumeMounts:
          - mountPath: /root/.gnupg
            name: release-gpg
          - name: image-cache
            mountPath: /image-cache            
          workingDir: /workspace/source
        steps:
        - env:
          - name: GIT_TOKEN
            valueFrom:
              secretKeyRef:
                key: password
                name: tekton-git          
          - name: GIT_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: tekton-git
          image: ghcr.io/jenkins-x/jx-release-version:2.5.0
          name: next-version
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx-release-version --tag --debug > VERSION
        - image: ghcr.io/jenkins-x/jx-boot:3.5.4
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: haskell:8.10.4
          name: build-cabal-all
          resources: {}
          script: |
            #!/bin/bash
            source .jx/variables.sh
            ./scripts/prereqs.sh
            ./scripts/cabal-build.sh
        - image: ghcr.io/jenkins-x/jx-registry:0.1.1
          name: check-registry
          resources: {}
        - image: gcr.io/kaniko-project/executor:v1.6.0-debug
          name: build-container-build
          resources: {}
          script: |
            #!/busybox/sh
            source .jx/variables.sh
            cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json
            /kaniko/executor $KANIKO_FLAGS \
              --context=/workspace/source \
              --dockerfile=${DOCKERFILE_PATH:-Dockerfile} \
              --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION
        - image: ghcr.io/jenkins-x/jx-changelog:0.3.0
          name: promote-changelog-uat
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            if [ -d "charts/$REPO_NAME" ]; then
            jx gitops yset -p version -v "$VERSION" -f ./charts/$REPO_NAME/Chart.yaml
            jx gitops yset -p appVersion -v "$VERSION" -f ./charts/$REPO_NAME/Chart.yaml
            jx gitops yset -p 'image.repository' -v $DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME -f ./charts/$REPO_NAME/values.yaml
            jx gitops yset -p 'image.tag' -v "$VERSION" -f ./charts/$REPO_NAME/values.yaml;
            else echo no charts; fi

            git add * || true
            git commit -a -m "chore: release $VERSION" --allow-empty
            git tag -fa v$VERSION -m "Release version $VERSION"
            git push --force origin v$VERSION

            jx changelog create --draft --version v${VERSION}
        - image: ghcr.io/jenkins-x/jx-changelog:0.3.0
          name: promote-changelog
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh

            if [ -d "charts/$REPO_NAME" ]; then
            jx gitops yset -p version -v "$VERSION-$BUILD_ID" -f ./charts/$REPO_NAME/Chart.yaml
            jx gitops yset -p appVersion -v "$VERSION-$BUILD_ID" -f ./charts/$REPO_NAME/Chart.yaml
            jx gitops yset -p 'image.repository' -v $DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME -f ./charts/$REPO_NAME/values.yaml
            jx gitops yset -p 'image.tag' -v "$VERSION-$BUILD_ID" -f ./charts/$REPO_NAME/values.yaml;
            else echo no charts; fi

            jx changelog create --version v${VERSION}

            git add * || true
            git commit -a -m "chore: release $VERSION" --allow-empty
            git tag -fa v$VERSION -m "Release version $VERSION"
            git push --force origin v$VERSION
        - image: golang:1.15
          name: upload-artifacts-release
          resources: {}
          script: |
            #!/usr/bin/env sh
            export GITHUB_TOKEN=${GIT_TOKEN}

            go get github.com/github-release/github-release
            github-release upload \
              --user $REPO_OWNER \
              --repo $REPO_NAME \
              --tag v${VERSION} \
              --name "$REPO_NAME-linux-amd64" \
              --file $ARTIFACT-${VERSION}
        - image: ghcr.io/jenkins-x/jx-boot:3.5.4
          name: promote-helm-release
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx gitops helm release --version $VERSION-$BUILD_ID
        - image: ghcr.io/jenkins-x-plugins/jx-promote:0.1.0
          resources: {}
          script: |
            #!/usr/bin/env sh
            source .jx/variables.sh
            jx promote -b --all --timeout 1h --version $VERSION-$BUILD_ID --no-poll
        volumes:
        - name: release-gpg
          secret:
            optional: true
            secretName: jenkins-release-gpg
        - name: image-cache
          persistentVolumeClaim:
            claimName: kaniko-docker-cache            
        workspaces:
          - name: source
            description: |
              Default Workspace
            optional: false
            mountPath: /workspace/source 
  serviceAccountName: tekton-bot
  timeout: 12h0m0s
status: {}
